jpms.server.app.port=8080

jpms.server.postgres.target=localhost:5432/app
jpms.server.postgres.user=app
jpms.server.postgres.pass=app
jpms.server.postgres.pool.size=10

jpms.server.elasticsearch.target=http://localhost:9200
